### ISSUE TITLE
Unicode character issues

### ISSUE THREAD

**Issue by abi** [sarenji/thermos#5]
@h1 '—' generates <h1>â€”</h1>. Gotta HTML escape the strings somewhere me thinks. Haven't tried to fix it yet, just ran into this while using Thermos.

**Comment by sarenji** [comment]
I don't think this is a thermos-specific issue. I tried this on `solid` without using thermos and it encodes wrongly there as well.

``` bash
$ curl localhost:9001
```

``` html
# in bash
—
```

``` coffeescript
# in the browser:
â€”
```

At least you can still use `&mdash;` for now.

**Comment by abi** [comment]
I'm saying Thermos should be an exemplar of always-does-the-right-thing-even-without-you-prodding-it and convert my `—` to `&mdash;`. I think other frameworks do such things. With underscore.string.js, it's `_.escapeHTML()`.

**Comment by sarenji** [comment]
The above commit and commit 5f0748e should fix your issues. Lemme know if there's any more entities you wanna automatically encode. Probably stuff like curly quotes.

**Comment by abi** [comment]
This isn't pushed to npm yet?

**Comment by sarenji** [comment]
Sorry, fixed.
