### ISSUE TITLE
html attributes?

### ISSUE THREAD

**Issue by activestylus** [sarenji/thermos#7]
I dont see any examples of this in the README. I am curious how you can manually specify attributes and also pass dynamic strings into them

**Comment by sarenji** [comment]
The meat is in the [`tag` function](https://github.com/sarenji/thermos/blob/master/src/thermos.coffee#L117-161). It checks the type of the arguments passed to the function. That's how all hashes are converted to attributes.

Does that answer your question?

**Comment by activestylus** [comment]
It definitely pushed me in the right direction. I should have looked at your [tests](https://github.com/sarenji/thermos/blob/master/test/templates.coffee#L48)

BTW - I really wasn't expecting the source to be so terse here. Really nice work

**Comment by activestylus** [comment]
There is one small thing that bothers me, and that is the convention of using underscores as attribute names. I say this as a primarily Ruby coder, but when I do any JS or CoffeeScript I adopt CamelCase. No biggie though - I will probably fork this puppy and get it working to my preference
